---
title: "Assignment 2"
author: "Hans"
date: "9/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(pacman)
p_load(tidyverse)
p_load(nycflights13)
p_load(ggplot2)
p_load(Deriv)
p_load(deSolve)
p_load(phaseR)
p_load(gridExtra)
theme_set(theme_minimal())
```


# Define the model and plot flow field, null clines and one trajectory
```{r define_model}

autocat_model = function(timepoint, state, parameters) { 
  with(as.list(c(state, parameters)), {
    dS1 = k0 - k1 * S1 * (1 + (S2/K)^n) 
    dS2 = k1 * S1 * (1 + (S2/K)^n)  - k2 * S2 
    list(c(dS1, dS2))
  }) 
}

# for setting the axis limits
xlim = c(-10, 20) 
ylim = c(-5, 5)

xlim = c(0, 2) 
ylim = c(0, 2)


pars = c(k0 = 0.1, k1 = 0.1, k2 = 0.1, K = 3, n = 3)

pars = c(k0 = 5, k1 = 2, k2 = 5, K = 1, n = 1)

#draw vector field
model.flowField = flowField(xlab = "S1", ylab = "S2", autocat_model,
                            xlim = xlim, ylim = ylim,
                            parameters = pars,
                            points = 19, add = FALSE,
                            state.names = c("S1", "S2"))

# draw nullclines
model.nullclines = nullclines(autocat_model, xlim = xlim, ylim = ylim,
                              parameters = pars,
                              points = 500, 
                              state.names = c("S1", "S2"))

# Determine stability
stab.expgrowth = stability(autocat_model, 
                           ystar = c(1,1), 
                           parameters = pars, 
                           system = "two.dim", 
                           state.names = c("S1", "S2")    # Do not forget this
                           )
# draw trajectory
model.trajectory = trajectory(autocat_model,
                              y0 = c(1, 1),
                              tlim = c(0, 10),
                              parameters = pars,
                              state.names = c("S1", "S2"))
model.trajectory = trajectory(autocat_model,
                              y0 = c(-0.5, 0),
                              tlim = c(0, 10),
                              parameters = pars,
                              state.names = c("S1", "S2"))
model.trajectory = trajectory(autocat_model, y0 = c(1.5, 3),
                              tlim = c(0, 10),
                              parameters = pars,
                              state.names = c("S1", "S2"))
model.trajectory = trajectory(autocat_model, y0 = c(5, -10),
                              tlim = c(0, 10),
                              parameters = pars,
                              state.names = c("S1", "S2"))

```


```{r}

# Perform numerical simulation and plot end result
# The function numericalSolution

model.numericalSolution = numericalSolution(autocat_model, 
                                            y0 = c(1, 1), 
                                            tlim = c(0, 20), 
                                            type = "one",
                                            parameters = pars, 
                                            state.names = c('S1', 'S2'),
                                            col = c("green", "orange"), 
                                            ylim = ylim, 
                                            add.legend = F)
legend("topright", col = c("green", "orange"), legend = c("x", "y"), lty = 1)
eq = locator(n = 1)

model.numericalSolution = numericalSolution(autocat_model, 
                                            y0 = c(1,2), 
                                            tlim = c(0, 20), 
                                            type = "one",
                                            parameters = pars,
                                            state.names = c('S1', 'S2'),
                                            col = c("green", "orange"), 
                                            ylim = ylim, 
                                            add.legend = F)
legend("topright", col = c("green", "orange"), legend = c("x", "y"), lty = 1)


model.numericalSolution = numericalSolution(autocat_model, 
                                            y0 = c(2, 1), 
                                            tlim = c(0, 20), 
                                            type = "one",
                                            parameters = pars, 
                                            state.names = c('S1', 'S2'),
                                            col = c("green", "orange"), 
                                            ylim = ylim, 
                                            add.legend = F)
legend("topright", col = c("green", "orange"), legend = c("x", "y"), lty = 1)


model.numericalSolution = numericalSolution(autocat_model, y0 = c(0, 5), 
                                            tlim = c(0, 20), type = "one",
                                            parameters = pars,
                                            state.names = c('S1', 'S2'),
                                            col = c("green", "orange"), 
                                            ylim = ylim, 
                                            add.legend = F)
legend("topright", col = c("green", "orange"), legend = c("x", "y"), lty = 1)


model.numericalSolution = numericalSolution(autocat_model, y0 = c(0, -5), 
                                            tlim = c(0, 20), type = "one",
                                            parameters = pars,
                                            state.names = c('S1', 'S2'),
                                            col = c("green", "orange"), 
                                            ylim = ylim, 
                                            add.legend = F)
legend("topright", col = c("green", "orange"), legend = c("x", "y"), lty = 1)

```



## Question 11

```{r define_model}


autocat_model = function(timepoint, state, parameters) { 
  with(as.list(c(state, parameters)), {
    dS1 = k0 - k1 * S1 * (1 + (S2/K)^n) 
    dS2 = k1 * S1 * (1 + (S2/K)^n)  - k2 * S2 
    list(c(dS1, dS2))
  }) 
}

# for setting the axis limits
xlim = c(-10, 20) 
ylim = c(-5, 5)

xlim = c(0, 5) 
ylim = c(0, 5)


pars = c(k0 = 0.1, k1 = 0.1, k2 = 0.1, K = 3, n = 3)

pars = c(k0 = 5, k1 = 2, k2 = 5, K = 1, n = 5)

#draw vector field
model.flowField = flowField(xlab = "S1", ylab = "S2", autocat_model,
                            xlim = xlim, ylim = ylim,
                            parameters = pars,
                            points = 19, add = FALSE,
                            state.names = c("S1", "S2"))

# draw nullclines
model.nullclines = nullclines(autocat_model, xlim = xlim, ylim = ylim,
                              parameters = pars,
                              points = 500, 
                              state.names = c("S1", "S2"))

# Determine stability
stab.expgrowth = stability(autocat_model, 
                           ystar = c(1,1), 
                           parameters = pars, 
                           system = "two.dim", 
                           state.names = c("S1", "S2")
                           )
# draw trajectory
model.trajectory = trajectory(autocat_model,
                              y0 = c(1, 1),
                              tlim = c(0, 10),
                              parameters = pars,
                              state.names = c("S1", "S2"))
# model.trajectory = trajectory(autocat_model,
#                               y0 = c(-0.5, 0),
#                               tlim = c(0, 10),
#                               parameters = pars,
#                               state.names = c("S1", "S2"))
# model.trajectory = trajectory(autocat_model, 
#                               y0 = c(1, 2),
#                               tlim = c(0, 10),
#                               parameters = pars,
#                               state.names = c("S1", "S2"))
# model.trajectory = trajectory(autocat_model, y0 = c(4, 5),
#                               tlim = c(0, 10),
#                               parameters = pars,
#                               state.names = c("S1", "S2"))

```

```{r}

# Perform numerical simulation and plot end result
# The function numericalSolution

model.numericalSolution = numericalSolution(autocat_model, 
                                            y0 = c(1, 1), 
                                            tlim = c(0, 20), 
                                            type = "one",
                                            parameters = pars, 
                                            state.names = c('S1', 'S2'),
                                            col = c("green", "orange"), 
                                            ylim = ylim, 
                                            add.legend = F)
legend("topright", col = c("green", "orange"), legend = c("x", "y"), lty = 1)
eq = locator(n = 1)

model.numericalSolution = numericalSolution(autocat_model, 
                                            y0 = c(1,2), 
                                            tlim = c(0, 20), 
                                            type = "one",
                                            parameters = pars,
                                            state.names = c('S1', 'S2'),
                                            col = c("green", "orange"), 
                                            ylim = ylim, 
                                            add.legend = F)
legend("topright", col = c("green", "orange"), legend = c("x", "y"), lty = 1)


model.numericalSolution = numericalSolution(autocat_model, 
                                            y0 = c(2, 1), 
                                            tlim = c(0, 20), 
                                            type = "one",
                                            parameters = pars, 
                                            state.names = c('S1', 'S2'),
                                            col = c("green", "orange"), 
                                            ylim = ylim, 
                                            add.legend = F)
legend("topright", col = c("green", "orange"), legend = c("x", "y"), lty = 1)


model.numericalSolution = numericalSolution(autocat_model, 
                                            y0 = c(4, 1), 
                                            tlim = c(0, 20), type = "one",
                                            parameters = pars,
                                            state.names = c('S1', 'S2'),
                                            col = c("green", "orange"), 
                                            ylim = ylim, 
                                            add.legend = F)
legend("topright", col = c("green", "orange"), legend = c("x", "y"), lty = 1)


model.numericalSolution = numericalSolution(autocat_model, 
                                            y0 = c(4, 1), 
                                            tlim = c(0, 20), type = "one",
                                            parameters = pars,
                                            state.names = c('S1', 'S2'),
                                            col = c("green", "orange"), 
                                            ylim = ylim, 
                                            add.legend = F)
legend("topright", col = c("green", "orange"), legend = c("x", "y"), lty = 1)

```
# Michaelis Menten

## Question 18

```{r Michaelis Menten}

library(deSolve)

mm = function(t, state, parameters) { 
  with(as.list(c(state, parameters)), {
    dS = -k1 * (E0 - C) * S + kmin1 * C
    dC =  k1 * (E0 - C) * S - kmin1 * C - k2 * C
    dP =  k2 * C 
    list(c(dS, dC, dP))
  }) 
}

pars = c(k1 = 1, kmin1 = 1, k2 = 1, E0 = 1)
inistate = c(S = 5, C = 0, P = 0)   # Important to have the same sequence!

time_series = seq(0, 50, by = 0.1)

out = ode(y = inistate, 
          times = time_series, 
          func = mm, 
          parms = pars)

df = data.frame(out)

p1 <- ggplot(data = df) +
  geom_line(mapping = aes(x=time, y = S), col= 'red') 
p2 <- ggplot(data = df) +
  geom_line(mapping = aes(x=time, y = C), col= 'blue') 
p3 <- ggplot(data = df) +
  geom_line(mapping = aes(x=time, y = P)) 

gridExtra::grid.arrange(
    p1,
    p2,
    p3,
    nrow = 2)

```

## Question 19

```{r}
 

dpdt <- function (S, Vmax, Km) {
  Vmax * S / (S + Km)
}

Vmax = 2
Km   = 1
s_seq = seq(0, 10, 0.1)
dpdt_seq = dpdt(s_seq, Vmax, Km)

dataf   <- data.frame(s_seq, dpdt_seq)

p <- ggplot(data = dataf)
p <- p + geom_line(mapping = aes(x = s_seq, y = dpdt_seq))
p <- p + labs(x = "S")
p <- p + labs(y = "dP/dt")
p <- p + xlim(-0.1, 10)
p <- p + labs(title = "New Plot", subtitle = "New subtitle")
p <- p + labs(caption = "(based on dummy data)")
p <- p + geom_vline(xintercept = 0 )
p <- p + geom_hline(yintercept = 0 )
p <- p + geom_vline(xintercept = Km, linetype = 'dashed') 
p <- p + geom_hline(yintercept = Vmax, linetype = 'dashed') 
p <- p + geom_hline(yintercept = Vmax/2, linetype = 'dashed') 
p

```


## Question 21

```{r}

mm = function(t, state, parameters) { 
  with(as.list(c(state, parameters)), {
    dS = -k1 * (E0 - C) * S + kmin1 * C
    dC =  k1 * (E0 - C) * S - kmin1 * C - k2 * C
    dP =  k2 * C 
    list(c(dS, dC, dP))
  }) 
}

mmqss = function(t, state, parameters) { 
  with(as.list(c(state, parameters)), {
    dS = -k2 * E0 * S / (S + (kmin1 + k2) / k1)
    dP =  k2 * E0 * S / (S + (kmin1 + k2) / k1)
    list(c(dS, dP))
  }) 
}

pars = c(k1 = 1, kmin1 = 1, k2 = 1, E0 = 1)

inistate     = c(S = 5, C = 0, P = 0)
inistate_qss = c(S = 5, P = 0)

time_series = seq(0, 50, by = 0.1)

out = ode(y = inistate, 
          times = time_series, 
          func = mm, 
          parms = pars)

outqss = ode(y = inistate_qss, 
             times = time_series, 
             func = mmqss, 
             parms = pars)

df = data.frame(out, outqss)

ggplot(data = df) +
  geom_line(mapping = aes(x=time, y = P), col= 'red', linetype = 'dotted') +
  geom_line(mapping = aes(x=time, y = P.1), col= 'blue') 


```