---
title: "Study"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r define_model}
library("phaseR")

# define 2D ODE model

model = function(timepoint, state, parameters) { 
  with(as.list(c(state, parameters)), {
    dx = x + 2*y 
    dy = 3*x + 2*y 
    list(c(dx, dy))
  }) 
}

# for setting the axis limits
xlim = c(-10, 10) 
ylim = c(-10, 10)

# no parameters in the ODE, so we set pars as an empty vector
pars = vector()
# draw vector field
model.flowField = flowField(xlab = "x", ylab = "y", model, 
                            xlim = xlim, ylim = ylim, 
                            parameters = pars, 
                            points = 19, add = FALSE, 
                            state.names = c("x", "y"))

# draw nullclines
model.nullclines = nullclines(model, xlim = xlim, ylim = ylim,
                              parameters = pars,
                              points = 500, state.names = c("x", "y"))

# draw trajectory
model.trajectory = trajectory(model, y0 = c(-8, 7), tlim = c(0, 10), 
                              parameters = pars, state.names = c("x", "y"))
model.trajectory = trajectory(model, y0 = c(-10, 9), tlim = c(0, 10), 
                              parameters = pars, state.names = c("x", "y"))
model.trajectory = trajectory(model, y0 = c(-10, 9.1), tlim = c(0, 10), 
                              parameters = pars, state.names = c("x", "y"))
model.trajectory = trajectory(model, y0 = c(-10, 9.2), tlim = c(0, 10), 
                              parameters = pars, state.names = c("x", "y"))
model.trajectory = trajectory(model, y0 = c(-9, 10), tlim = c(0, 10), 
                              parameters = pars, state.names = c("x", "y"))
model.trajectory = trajectory(model, y0 = c(-9, 9.8), tlim = c(0, 10), 
                              parameters = pars, state.names = c("x", "y"))
model.trajectory = trajectory(model, y0 = c(-9, 9.7), tlim = c(0, 10), 
                              parameters = pars, state.names = c("x", "y"))
model.trajectory = trajectory(model, y0 = c(-5, 6), tlim = c(0, 10), 
                              parameters = pars, state.names = c("x", "y"))
```

# Calulate the x and y over time with varying start conditions
```{r}
# perform numerical simulation and plot end result
model.numericalSolution = numericalSolution(model, y0 = c(-5, -5), 
                                            tlim = c(0, 20), type = "one",
                                            parameters = pars, 
                                            col = c("green", "orange"), 
                                            ylim = ylim, add.legend = F)
# make legend for plot
legend("topright", col = c("green", "orange"), legend = c("x", "y"), lty = 1)
eq = locator(n = 1)

model.numericalSolution = numericalSolution(model, y0 = c(5, 10), 
                                            tlim = c(0, 20), type = "one",
                                            parameters = pars, 
                                            col = c("green", "orange"), 
                                            ylim = ylim, add.legend = F)
# make legend for plot
legend("topright", col = c("green", "orange"), legend = c("x", "y"), lty = 1)


model.numericalSolution = numericalSolution(model, y0 = c(-5, 5), 
                                            tlim = c(0, 20), type = "one",
                                            parameters = pars, 
                                            col = c("green", "orange"), 
                                            ylim = ylim, add.legend = F)
# make legend for plot
legend("topright", col = c("green", "orange"), legend = c("x", "y"), lty = 1)

```
```

# Question 1: Calculate the stability at the selected equilibrium
```{r}

stab = stability(model, parameters = pars, system = "two.dim",
                 ystar=c(0, 0), state.names = c("x", "y"))
```

